TOP=../..
include $(TOP)/configure/CONFIG


DB += BPM.db
DB += COR.db
DB += InvalidInCell.db
DB += Cell_Merge.db
DB += BPM_Cycle.db
DB += Orb_Merge.db
DB += ORM.db
DB += SOFB_SP.db
DB += CorSP.db
DB += CorSP_Merger.db
DB += SR.db

#DB += vBPM.template
#DB += vCOR.template
#DB += vCOR2SR.template
#DB += vBPM.substitutions
#DB += vCOR.substitutions
#DB += vCOR2SR.substitutions
#DB += vSR.db



#DB += refOrbParse.db

include $(TOP)/configure/RULES

